# Generated by Django 5.1.6 on 2025-03-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Numele invitatului', max_length=100)),
                ('email', models.EmailField(help_text='Adresa de email a invitatului', max_length=254)),
                ('message', models.TextField(blank=True, default='', help_text='Mesaj opțional')),
                ('attending', models.BooleanField(default=False, help_text='Indică dacă persoana va participa la nuntă')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data și ora la care a fost trimis RSVP-ul')),
            ],
        ),
    ]
